swiftmailer:
#        url: '%env(MAILER_URL)%'
#        spool: { type: 'memory' }
    transport:        smtp
    username:         test@pianolekcje.pl
    password:         Getrich12#
    host:             smtp.dpoczta.pl
    port:             578
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    # stream_options:
    #     ssl:
    #         allow_self_signed: true
    #         verify_peer: false
    #         verify_peer_name: false
